_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
            "2":
                - 1
                - 11
                - 49
                - 55
                - 71
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.0
            "5": 0.19.8
            "6": 4.41.1
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
batch_size:
    value: 16
dataset_path:
    value: ./data/theorems.json
embedding_dim:
    value: 768
epochs:
    value: 3
evaluation:
    value:
        recall_k:
            - 1
            - 5
            - 10
experiment_name:
    value: baseline-contrastive
freeze_bert:
    value: false
learning_rate:
    value: 2e-05
loss_type:
    value: contrastive
margin:
    value: 1
max_seq_length:
    value: 128
model_name:
    value: bert-base-uncased
project_name:
    value: coq-theorem-embedding
random_seed:
    value: 52
test_split:
    value: 0.1
threshold_neg:
    value: 50
threshold_pos:
    value: 10
train_split:
    value: 0.8
val_split:
    value: 0.1
wandb:
    value:
        enabled: true
        entity: kozyrev-andreiii2016
        project: coq-embeddings
        tags:
            - baseline
            - contrastive
