project_name: "coq-theorem-embedding"
experiment_name: "infonce-file-final-1"
log_level: "INFO"

dataset_path: "./data/"
rankin_ds_path_statements: "./data/imm/basic/Events_statements.json"
rankin_ds_path_references: "./validationSet/reference_premises.json"
samples_from_single_anchor: 150
train_split: 0.8
val_split: 0.2
test_split: 0.0

model_name: "microsoft/codebert-base"
max_seq_length: 128
embedding_dim: 768

margin: 0.25
# proof distance <= threshold -> positive
threshold_pos: 0.3
# proof distance >= threshold -> negative
threshold_neg: 0.65
threshold_hard_neg: 0.45
k_negatives: 4

output_dir: "./checkpoints/"
steps: 100000
eval_steps: 200
evaluate_freq: 100
save_freq: 300
batch_size: 32
warmup_ratio: 0.1
learning_rate: 4e-6
random_seed: 52

wandb:
  enabled: true
  project: "coq-embeddings"
  entity: "kozyrev-andreiii2016"
  tags: ["baseline", "triplet"]

evaluation:
  # For precision@k and recall@k
  k_values: [15]
  f_score_beta: 1
  query_size_in_eval: 20